/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CoinBlock: typeof import('./components/CoinBlock.vue')['default']
    CoinItem: typeof import('./components/CoinItem.vue')['default']
    CoinSelect: typeof import('./components/CoinSelect.vue')['default']
    ConfirmModal: typeof import('./components/ConfirmModal.vue')['default']
    DataBlock: typeof import('./components/DataBlock.vue')['default']
    Error: typeof import('./components/Error.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sceleton: typeof import('./components/Sceleton.vue')['default']
    SubmitStatus: typeof import('./components/SubmitStatus.vue')['default']
    TransactionForm: typeof import('./components/TransactionForm.vue')['default']
  }
}
