/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Assets: typeof import('./views/Assets.vue')['default']
    AuthLayout: typeof import('./layout/AuthLayout.vue')['default']
    CoinItem: typeof import('./components/CoinItem.vue')['default']
    CoinSelect: typeof import('./components/CoinSelect.vue')['default']
    DefaultLayout: typeof import('./layout/DefaultLayout.vue')['default']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    Header: typeof import('./components/Header.vue')['default']
    Home: typeof import('./views/Home.vue')['default']
    NotFound: typeof import('./views/NotFound.vue')['default']
    PortfolioView: typeof import('./views/PortfolioView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubmitStatus: typeof import('./components/SubmitStatus.vue')['default']
    TransactionForm: typeof import('./components/TransactionForm.vue')['default']
    TransactionsView: typeof import('./views/TransactionsView.vue')['default']
  }
}
